import Head from "next/head";
import Navigation from "../components/navigation";
import Paragraph from "../components/Paragraph";
import PSection from "../components/PSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <PSection alt={false} title="About" image="/about.jpg">
        <Paragraph>
          J.O.Y – The Free Resources Clinic is a faith-based organization
          providing free information and health resources to those who are
          either uninsured or underinsured and without access to available care
          services in the Oklahoma City community. ... becomes even more
          profound on vulnerability and unmet health care.
        </Paragraph>
      </PSection>
      <main className="space-y-8 lg:pl-48 lg:pr-48 md:pl-28 md:pr-28"></main>
    </div>
  );
}

const sections = [
  {
    title: "Prevention",
    image: "/prevention.jpg",
    child: (
      <Paragraph>
        J.O.Y. The Free Resources Clinic believes in Prevention. It is a
        healthcare choice that will answer questions/concerns with possible
        solutions and will make the health journey a healing one from inside and
        out. As we understand, healing is a process just as prevention is a
        process but when we prevent a disease early on, healing becomes
        something of the past.
      </Paragraph>
    ),
  },
  {
    title: "Advocacy",
    image: "/advocacy.jpg",
    child: (
      <Paragraph>
        J.O.Y. The Free Resources Clinic believes in Prevention. It is a
        healthcare choice that will answer questions/concerns with possible
        solutions and will make the health journey a healing one from inside and
        out. As we understand, healing is a process just as prevention is a
        process but when we prevent a disease early on, healing becomes
        something of the past.
      </Paragraph>
    ),
  },
  {
    title: "Advocacy",
    image: "/advocacy.jpg",
    child: (
      <Paragraph>
        J.O.Y. The Free Resources Clinic believes in Prevention. It is a
        healthcare choice that will answer questions/concerns with possible
        solutions and will make the health journey a healing one from inside and
        out. As we understand, healing is a process just as prevention is a
        process but when we prevent a disease early on, healing becomes
        something of the past.
      </Paragraph>
    ),
  },
];
