import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/navigation";
import PSection from "../components/PSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main className="lg:pl-48 lg:pr-48 md:pl-28 md:pr-28">
        <PSection />
      </main>
    </div>
  );
}




