import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/navigation";
import PSection from "../components/PSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <main className="space-y-8 lg:pl-48 lg:pr-48 md:pl-28 md:pr-28">
        <PSection title={sections[0].title} image={sections[0].image}>
          {sections[0].child}
        </PSection>
        <PSection alt={true} title={sections[0].title} image={sections[0].image}>
          {sections[0].child}
        </PSection>
      </main>
    </div>
  );
}

const sections = [
  {
    title: "Prevention",
    image: "/prevention.jpg",
    child: (
      <>
        J.O.Y. The Free Resources Clinic believes in Prevention. It is a
        healthcare choice that will answer questions/concerns with possible
        solutions and will make the health journey a healing one from inside and
        out. As we understand, healing is a process just as prevention is a
        process but when we prevent a disease early on, healing becomes
        something of the past.
      </>
    ),
  },
];
